name: Extract
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Git Clone sing-box-subscribe
          run: |
            echo "Python DEV"
            python3 --version
            python3 -m pip install --upgrade pip -q
            pip install -r  requirements.txt -q
            echo "Get providers.toml"
            echo "${{ vars.PROVIDERS }}" > providers.toml
            echo "Validate providers.toml"
            python3 main.py